on: 
  push:
    branches:
       main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Adjust if different build command
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 166.62.28.131
        username: school@theschoolster.in
        password: Admin123@#
        local-dir: build
